spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/deal
    password: postgres
    username: postgres

integration:
  conveyor:
    client:
      url: http://localhost:8010
  dossier:
    bootstrap-servers: localhost:9092