server:
  port: 8012

logging:
  level:
    org.zalando.logbook: TRACE

logbook:
  exclude:
    - /actuator/**
    - /swagger-ui/**
    - /v3/api-docs/**

integration:
  deal:
    client:
      url: ${INTEGRATION_DEAL_CLIENT_URL}
      connect-timeout: 300
      read-timeout: 300
      write-timeout: 300