server:
  port: 8013
sender:
  mail:
    account: ${CONVEYOR_MAIL_ACCOUNT}
spring:
  kafka:
    consumer:
      bootstrap-servers: ${DOSSIER_CONSUMER_BOOTSTRAPSERVERS}
      group-id: ${DOSSIER_CONSUMER:dossier-consumer}
      auto-offset-reset: earliest
      isolation-level: read_committed
  mail:
    host: ${CONVEYOR_MAIL_HOST}
    port: ${CONVEYOR_MAIL_PORT}
    username: ${sender.mail.account}
    password: ${CONVEYOR_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          ssl:
            enable: true
          starttls:
            enable: true

